- frontend/src/app/Navigation/index.jsx
changed from using the `a` tag to using the react router for navigating to the homepage
> fix: logo uses router to navigate to dashboard

- .github/workflows/codesee-arch-diagram.yml
This pull request adds the CodeSee workflow to your repository.
This workflow runs a code analysis on each time:
a new PR is opened
a new commit is pushed to an existing PR
a PR is merged or a new commit is pushed directly to the default branch
The analysis enables [code visibility](https://www.codesee.io/what-is-code-visibility) for your codebase: generating maps of your codebase, keeping existing maps up-to-date, and automating code workflows.
Access the CodeSee web app at https://app.codesee.io/ or learn more at https://docs.codesee.io/. If you have any questions, please reach out to [support@codesee.io](mailto:support@codesee.io) and we'll be happy to help.
> Install the CodeSee workflow. Learn more at https://docs.codesee.io

- controllers/corsControllers/apiRest.js
> Remove Console.log in apiRest.js

- frontend/src/modules/PaymentModule/DataTableDropMenu.jsx
- frontend/src/modules/PaymentModule/index.jsx
- frontend/src/pages/Invoice.jsx
- frontend/src/pages/PaymentInvoice.jsx
This pull request address issue #270. change the code structure of the Payment Invoice module to a dedicated component structure. and adding new actions 'Download' for the data.
> Add button action for download receipt at Payment Invoice

- frontend/src/style/partials/core.less
after trying to merge the responsive table PR
there was a conflict in core.less i fixed it in GitHub but I didnt pay attention to closing brackets and created this issue
but this pr will fix it
> fix: core.less issue

- frontend/src/modules/CrudModule/index.jsx
This pull request directly addresses issue  #383
Remove mail button from `frontend\src\modules\CrudModule\index.jsx` and unnecessary imports.
> fix: removed mail button from CrudModule

- frontend/src/components/Notification/index.jsx
- frontend/src/style/partials/header.less
fixed the styling for the dropdown
linking to the notifications api
> fix: notification dropdown frontend

- controllers/erpControllers/invoiceController.js
- controllers/erpControllers/offerController.js
- controllers/erpControllers/paymentInvoiceController.js
- controllers/erpControllers/quoteController.js
On successful creation of ERP controllers, a generic message "created document in model" was displayed to the user. This is bad for user experience, as it does not give the user any information about what document was created.
This PR updates the message to be more model-specific for custom controllers. For example, if a new invoice is created, the message will be `created invoice`
Before
After
Improve creation messages for other non-custom controllers such as Employee
> feat: better alert messages for custom ERP controllers

- frontend/src/pages/Currency.jsx
- frontend/src/pages/PaymentMode.jsx
- frontend/src/pages/Profile.jsx
- frontend/src/pages/Quote/index.jsx
This PR fixes the capitalization of page titles. In some pages, the titles were not capitalized, while in others they were.
For Quotes List page
Before
After
> fix: UI consistency

- controllers/erpControllers/invoiceController.js
- frontend/src/layout/ErpLayout/index.jsx
- frontend/src/modules/InvoiceModule/ReadInvoiceModule/index.jsx
- frontend/src/modules/InvoiceModule/UpdateInvoiceModule/index.jsx
- frontend/src/modules/QuoteModule/QuoteDataTableModule/components/DataTableDropMenu.jsx
- frontend/src/modules/QuoteModule/ReadQuoteModule/index.jsx
- frontend/src/modules/QuoteModule/UpdateQuoteModule/index.jsx
- frontend/src/style/partials/core.less
- frontend/src/utils/calculate.js
- helpers.js
fix invoice-quote
fix read-edit
add no-found
> fix invoice-quote

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- frontend/src/modules/InvoiceModule/Forms/InvoiceForm.jsx
- frontend/src/modules/PaymentInvoiceModule/Forms/PaymentInvoiceForm.jsx
- frontend/src/modules/QuoteModule/Forms/QuoteForm.jsx
Please provide a brief description of the changes or additions made in this pull request.
> Pr patch pull request template

- frontend/src/modules/ErpPanelModule/CreateItem.jsx
- frontend/src/modules/ErpPanelModule/RecordPayment.jsx
fixes #480 
#480 
Before:-
After:-
> fixed:#480payment-not-recorded-fixed

- frontend/src/modules/ErpPanelModule/CreateItem.jsx
- frontend/src/modules/ErpPanelModule/RecordPayment.jsx
Reverts idurar/idurar-erp-crm#482
> Revert "fixed:#480payment-not-recorded-fixed"

- frontend/src/app/Navigation/index.jsx
- frontend/src/forms/AdvancedSettingsForm.jsx
- frontend/src/pages/AdvancedSettings.jsx
- frontend/src/router/RoutesConfig.jsx
created a new page settings/advaced with crudModel to add new settings 
@salahlalami deleting a setting does not work because it is commented in the coreApi file
> feat : created a new page for advanced settings

- controllers/erpControllers/leadController.js
- models/erpModels/Lead.js
- routes/erpRoutes/erpApi.js
This PR is closing the Feature request #389
> Created endpoints for the Lead endpoint

- frontend/src/modules/ErpPanelModule/RecordPayment.jsx
putting back reverted changes that were merged directly into master now i'm adding them to dev branch
> the reverted code

- frontend/src/redux/crud/actions.js
- frontend/src/redux/erp/actions.js
Fixes #493 by adding an additional dispatch i.e. RESET_ACTION 
#493 
before:-
After:-
> fix:#493 resolved succesive deletion issue

- frontend/src/modules/ErpPanelModule/ReadItem.jsx
- frontend/src/modules/ErpPanelModule/UpdateItem.jsx
Fixes #498 
#498 
1. Open dashboard
2. Select show option on any invoice from Recent invoices section 
3. Now cick on the back button on header
> fix:#498 resolved back button issue

- README.md
- controllers/erpControllers/invoiceController.js
- controllers/erpControllers/quoteController.js
In the controller added a check that if `items` is empty then inform the user to provide that
#272
> added check for items

- frontend/src/components/SidePanel/index.jsx
- frontend/src/modules/AdminCrudModule/index.jsx
- frontend/src/modules/CrudModule/index.jsx
added the close btn for admin panel 
removed the back btn from the panel since it is same
no issue
> fix admin panel close button

- frontend/src/forms/LoginForm.jsx
- frontend/src/forms/RegisterForm.jsx
Added email pattern validation using regex: "[a-z0-9]+@[a-z]+.[a-z]{2,3}" and added confirm password check.
@polymahh @salahlalami
> add: email validation and confirm password checks

- README.md
Please provide a brief description of the changes or additions made in this pull request.
Basically, there is one open issue the front end is not set up. There is some error regarding OpenSSL. I have raised this MR for the solution of error removal. I have updated the frontend setup steps in the readme so that from now onwards no one will stuck into frontend setup
#303
> fix: Improve README.md to solve frontend setup issues

- frontend/src/components/DataTable/index.jsx
- frontend/src/modules/ErpPanelModule/DataTable.jsx
- frontend/src/redux/crud/actions.js
- frontend/src/redux/erp/actions.js
https://www.loom.com/share/96c6f6e6ca0643aaa0fb4cd8fb46c1e4?sid=2ff5910d-40e9-4928-83c0-948eaa58c132
> Pagination limit fix#446

- frontend/src/modules/ErpPanelModule/ItemRow.jsx
- views/pdf/PaymentInvoice.pug
- Fixed payment/invoice/edit from breaking
- Updated pug to support Payment Invoice
- #489 
- Go to 'payment/invoice'
- Click on 'download'
> Fix the bug for download payment receipt which returns invoice pdf instead of payment receipt 489

- frontend/src/style/partials/navigation.less
> fix for navigation scroll

- setup/config/appConfig.json
- setup/config/companyConfig.json
- setup/config/crmConfig.json
- setup/config/emailTemplate.json
- setup/config/financeConfig.json
- setup/setup.js
```javascript
// new json config : 
await Setting.insertMany([
...appConfig,
...companyConfig,
...financeConfig,
...emailTemplate,
...crmConfig,
...customConfig,
]);
```
> update settings config json files

- setup/setup.js
Running setup successfully gives a successful message and exits the process
#550
> feature:#550 added exit on setup and success message

- controllers/appControllers/paymentInvoiceController/summary.js
Dsahboard giving error code 500 fixed 
#547
> fixed:#547 fixed dashboard error

- README.md
Updated the getting started instructions in README.md w.r.t the recent changes made to the folder structure
> update getting started in readme.md w.r.t recent folder structure change

- backend/controllers/appControllers/taxController.js
- backend/models/appModels/Tax.js
- backend/routes/appRoutes/appApi.js
Added tax CRUD on backend
Issue: https://github.com/idurar/erp-crm/issues/544
I have tested it on Postman
Can create new tax with TaxName (string) and TaxValue (number).
Also can provide some other fields such as `isDefault`, `created`, `removed` and `enabled`
So on Postman (or other app) we can:
- create new tax with route POST `/api/taxes/list` and with data `{"taxName": "taxName", "taxValue": 123}`
- then get all list of taxes GET `/api/taxes/list` and being sure that our new tax in the list
- check reading by ID GET `/api/taxes/read/:id`
- check updating the tax PATCH `api/taxes/update/:id`
create a tax
Read the tax
Update the tax
Also, this some logic about default tax and enabling it
We have default tax and we …
> feat: add tax CRUD

- backend/controllers/appControllers/invoiceController/create.js
- backend/controllers/appControllers/offerController/create.js
- backend/controllers/appControllers/paymentInvoiceController/create.js
- backend/controllers/appControllers/quoteController/create.js
- backend/middlewares/permission.js
- backend/models/appModels/Client.js
- backend/models/appModels/Invoice.js
- backend/models/appModels/Lead.js
- backend/models/appModels/Offer.js
- backend/models/appModels/PaymentInvoice.js
- backend/models/appModels/Quote.js
- frontend/src/pages/Invoice/index.jsx
Please provide a brief description of the changes or additions made in this pull request.
> add createdBy to invoice table

- backend/controllers/coreControllers/authJwtController/login.js
- frontend/src/config/serverApiConfig.js
- frontend/vite.config.js
Reverts idurar/idurar-erp-crm#619
> Revert "fixed"

- frontend/src/forms/CustomerForm.jsx
- frontend/src/pages/Customer/index.jsx
Fixed reversed Manager first name and last name.
> Fix #634 Reversed Manager Firstname and Surname

- frontend/src/forms/CustomerForm.jsx
> Fix: phone number not working

- frontend/src/locale/translation/it_it.js
> Fix wrong typing in IT translation

- frontend/src/locale/translation/hi_in.js
Hindi Language Updated With New Words As You Added  Few New Words in English
everything is working perfectly fine
> hindi_lang_updated wuith new words

- backend/controllers/appControllers/quoteController/summary.js
> fixed Quote summary

- frontend/src/apps/components/Navigation.jsx
- frontend/src/forms/TaxForm.jsx
- frontend/src/locale/translation/en_us.js
- frontend/src/locale/translation/it_it.js
- frontend/src/pages/Taxes/index.jsx
- frontend/src/router/AppRouter.jsx
> added taxes page

- frontend/src/pages/Settings/Settings.jsx
Updated the moneyFormatSettings icon.
> fix: change moneyFormatSettings icon

- backend/middlewares/permission.js
I updated the permission message in the
> updated the permission message 

- frontend/src/components/MoneyInputFormItem/index.jsx
- frontend/src/modules/InvoiceModule/Forms/InvoiceForm.jsx
- frontend/src/modules/OfferModule/Forms/OfferForm.jsx
- frontend/src/modules/QuoteModule/Forms/QuoteForm.jsx
> bug fix: taxes not calculated correctly

- frontend/src/redux/translate/actions.js
Text direction gets change from RTL to LTR (for Arabic, Urdu language) after Refreshing the page.
Text direction gets change from RTL to LTR (for Arabic, Urdu language) after Refreshing the page. #795
1. Before this change, the text direction for Arabic, Urdu etc. language gets change from RTL to LTR while Hard Reloading Or Refreshing page, but after this update, this issue will be fix and work properly for all languages.
2. After merge the changes of this pull request, now do same first step. You will see the text direction not change during Refreshing page.
Before this pull request merge change, Select the Urdu or Arabic language & Refresh the change: 
After this pull request merge change, Select the Urdu or Arabic language & Refresh the change: 
-  I have tested these changes
-  I have …
> Text direction issue fixed on Refresh or hard reload page.

- README.md
i only changed the README.md  . new contributers can easly understant and code now , before cd backend cammad not in README.md . so i not tested the code
> Updated README.md  ,  cd backend cammand provided

- backend/src/controllers/middlewaresControllers/createAuthMiddleware/isValidAuthToken.js
- backend/src/handlers/errorHandlers.js
closes: #914 
fixed a typo in the backend :-
conttroller -> controller
> fix: Typo mistake in backend

- INSTALLATION-INSTRUCTIONS.md
- README.md
I removed the installation steps from the README.md file and moved them to a new file called INSTALLATION-INSTRUCTIONS.md.
I also added links in the README.md file to each of the specefic section in  INSTALLATION-INSTRUCTIONS.md file.
I also added a feature section in README.md file.
I added the Demo Credentials as it's way accessible for a person visiting this project for the first time
#527  
**INSTALLATION-INSTRUCTIONS.md file :**
**README.md file:**
_-Credentials part_
_-Features part_
_- Getting started links_
> Updated README.md file and added INSTALLATION-INSTRUCTIONS.md file

- README.md
- doc/README.fr.md
I created a doc folder in which i placed a README.fr.md : the translated README.md in french.
I also added a link in the original README.md file under the Translation Label to direct the user to the french version of the file when clicking on it.
#950 
_This is the added link in the original README.md:_
_This is the translated README.md in the doc folder_
> README.md translation in frensh

- README.md
- doc/README.sp.md
Inside the doc folder i added a README.sp.md : the translated README.md in spanish.
I also added a link in the original README.md file under the Translation Label to direct the user to the spanish version of the file when clicking on it.
#950 
This is the added link in the original README.md:
This is the translated README.md in the doc folder
> Spanish translation of README.md

- backend/src/utils/currency.js
- frontend/src/pages/Currency/currencyList.js
This pull request adds support for the Venezuelan Bolívar (VES) currency to our application. The issue 1058 has been resolved by updating the currency list to include VES as a valid currency code.
#1058 
1 in the currency section in a new invoice click on currency
2 click on add new currency
3 currencyList will appear then click on add new currency on the left 
4 Type VES on currency code and it will appear
>  Add Support for Venezuelan Bolívar (VES) currency

- backend/src/controllers/appControllers/clientController/migrate.js
- backend/src/controllers/appControllers/leadController/migrate.js
Fixed notes Not showing in Leads
Can't save notes in oportunities #1085
- Open the dashboard
- Go to leads tab 
- Click on the more tab
- In the show popup check for the notes property. 
- Before fixing it the notes where not showing.
- Now the notes field contains the correct value.
The before screenshot is found in the issue description.
This is the screenshot after correcting the issue.
- [X ] I have tested these changes
- [ X] I have updated the relevant documentation
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the codebase
- [ X] My changes generate no new warnings or errors
- [ X] The title of my pull request is clear and descriptive
> Fixed Notes Not Showing In Leads
