idurar/idurar-erp-crm

- frontend/src/components/SidePanel/index.jsx
- frontend/src/modules/CrudModule/index.jsx
Fixed #305 mobile navigation button overlap in customer page by adding the back button in customer panel and removing the menu button for add new customer panel
https://github.com/idurar/idurar-erp-crm/assets/56465357/e7c4ca88-98c3-4752-b2e1-0fc6958f4a72
> fix:fixed mobile navigation button overlap in customer page

- frontend/src/app/Navigation/index.jsx
Corrected the issue #306  where the menu is not being highlighted if the page is visited by changing the url. Raising pr again as per request
https://github.com/idurar/idurar-erp-crm/assets/56465357/e16ef2fb-5106-47af-9c0a-843a210adcd1
> fix: menu not highlighted while navigating via url fixed -2

- frontend/src/forms/PaymentInvoiceForm.jsx
I have added a constraint on the feild.
> [frontend bug fix] input feild min const. added]

- frontend/src/components/CreateForm/index.jsx
- frontend/src/forms/CustomerForm.jsx
Show error when the user inputs empty string into input item, trim data before making HTTP call to the server.
- Need to apply this validator to another form: Employee, Login, Payment, Role,...
> [Fix][FrontEnd] Handle empty string for customer form input

- frontend/src/modules/ErpPanelModule/UpdateItem.jsx
after clicking on update in erp module the update page stays open 
now it should redirects to entity/read/id
no issue
> fix: clicking on update redirects to read page

- controllers/erpControllers/clientController.js
Added delete method in clientController.js which deletes the client if there is no quote or invoice corresponding to that client 
Return error message if there is any  quote or invoice
Bug : Backend we can't remove client if they have at least one invoice or one quote #515
Create a client now add invoice or quote corresponding to that client you have created
Now try to delete this client you won't we able to delete and it shows message there invoice or quote corresponding to this client
Now delete the quote and invoice corresponding to that client and now you will be able to delete the client  
[video link](https://youtu.be/n6Pgyi9bmQ8)
> fix:Backend we can't remove client if they have at least one invoice or one quote #515

- frontend/src/components/SelectAsync/index.jsx
- frontend/src/forms/PaymentInvoiceForm.jsx
If list is empty 
it will show add Payment . On clicking it user will be redirected to add payment mode page. 
else 
it will show only payment modes. on clicking that modes , user can select them
#496
> Feat : Add redirect button to SelectAsync Comp if options is empty

- frontend/src/pages/Settings/PaymentSettings.jsx
Tax feild can be setting negative which is not possible I have add a constraint min should be 0.
1. Go to /settings
2. Click on the payment settings
3. Then on the tax field.
> constraint added on tax feild

- frontend/src/components/MultiStepSelectAsync/index.jsx
Created a new Multi-Step Select Async Component
#94
Hey @salahlalami, please check my changes and give me your feedback, It's just something I got from the description of the issue and created it. please provide me with some details of the project that I need to know for better work, I am interested in having daily PRs
> feat: Create new component multi step select async

- frontend/src/modules/ErpPanelModule/ItemRow.jsx
1. Added a pattern in rules attribute of <Form.Item> component which contain  "Item Name" input (file address : 
frontend/src/modules/ErpPanelModule/ItemRow.jsx).
2. This pattern contains regular expression which validate that "Item Name must contain alphanumeric or special characters" in 
real time.
Able to add fields in invoices without item name https://github.com/idurar/erp-crm/issues/207
Create or edit invoice and while adding items in invoice, you can check it.
https://ibb.co/mzM9sM7
- [ x ] I have tested these changes
- [ x ] I have updated the relevant documentation
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the codebase
- [ x ] My changes generate no new warnings or errors
- [ x ] The title of my pull …
> fix: Able to add fields in invoices without item name idurar#207

- frontend/src/forms/AdvancedSettingsForm.jsx
- frontend/src/pages/AdvancedSettings.jsx
added new form to create advanced settings
this is only frontend change might break creation of new setting when type == select
https://github.com/idurar/erp-crm/issues/541
> feat: new dynamic advanced settings

- frontend/src/modules/DashboardModule/components/SummaryCard.jsx
- frontend/src/modules/DashboardModule/index.jsx
Fixed the money format in the dashboard's cards using moneyFormatter of the useMoney hook.
> Fixed money format

- backend/setup/config/appConfig.json
Running node .\setup\setup.js gets this error: 
`MongoBulkWriteError: E11000 duplicate key error collection: idurar.settings index: settingKey_1 dup key: { settingKey: "app_name" }`
So I have updated the settings value in appConfig.json and then it runs the setup correctly.
> fix setup app setting

- backend/controllers/appControllers/invoiceController/summary.js
- backend/controllers/appControllers/offerController/summary.js
- backend/controllers/appControllers/quoteController/summary.js
- backend/controllers/appControllers/supplierOrderController/summary.js
When setting EURO as currency, decimal separator as "," and thousand separator as " ' " the summary cards show € 400,00 instead of € 4,00.
Removing toFixed(2) works with both euro configuration and dollar configuration. So the api response's total will be 4 instead of 4.00.
Try it before merge.
> bug fix: removed toFixed(2)

- frontend/src/modules/InvoiceModule/Forms/InvoiceForm.jsx
While creating new Invoice, the Status field have 3 values (Draft, Pending, and Pending). "Pending" is coming two times. I have checked the code, the 'value' on Select component is 'Sent' but 'label' is set as 'Pending' which is wrong.
#797 
1. Go to 'Invoice' tab
2. Click on 'Add new Invoice'
3. Expand Status field
4. Notice that Status field is showing three values with no repetition
Before:
After:
> fix: Change Pending to Sent Label

- frontend/src/modules/EmailModule/ReadEmailModule/components/ReadItem.jsx
For going back to the email templates list page, history.goBack() was used but history object was never defined. I replaced history.goBack() with navigate(`/${entity.toLowerCase()}`); which is working fine. This approach is also used while pressing Close button.
[#802 ](https://github.com/idurar/idurar-erp-crm/issues/802)
1. Go to 'Settings'
2. Click on 'Email Templates'
3. Click on Dropdown in front of any email template > Show
4. Click on back button
5. Notice that, user can go back which was not working previously.
> fix: back button on Read email template

- frontend/src/locale/translation/zh_cn.js
Taxes Keys Are Not Set In Chinese Localization Json File
#837
I has just not Displaying In English Language
> add taxes to Chinese Localization

- frontend/src/apps/components/Navigation.jsx
Added styling fot the Ant Design drawer
- Enable transparency
- Remove box shadow
- Increased the width for better transition fluidity
- Removed the css class as it was not affecting the component
https://github.com/idurar/idurar-erp-crm/issues/854
1. Visit Home page
2. Login as admin
3. Shrink the screen size to minimum or use Dev tools to view the app in mobile
4. Open the side nav to observe the white background behind the navbar.
Before :  
After :
> Fix  : Resolve drawer wrapper style for side-nav in mobile view

- frontend/src/modules/DashboardModule/index.jsx
The changes applied in this pull request standardize the display of tags whether the value is zero or not.
So, before the pull request, the null tags looked like this:
Now they look like this:
Technical Explanation : 
Given that the moneyFormatter() function defines a default argument equal to 0 if the latter is not defined, it is not useful to check the state of "result?.total" before calling the function.
This PR is supposed to fix the issue : #857 
To test the solution:
1) go to the dashboard
2) place your cursor on one of the prices (null or non-null) of the summary thumbnails.
3) Tags should all follow the same “currency price” format (ex: $ 0.00; $ 3,000.00)
> Fix: display of the tag when the value is zero #857

- frontend/src/modules/ErpPanelModule/ReadItem.jsx
I added the translation to the payment status and status in the show feature.
#881
1. Go to the invoice/offer/quote list
2. Click on the 3 dots of one of the items
3. Click on "Show"
4. change your language 
5. See that the status is now displayed in the language you chose and not in english.
> add translation of payment status and status in show feature

- frontend/src/modules/InvoiceModule/RecordPaymentModule/components/Payment.jsx
I added the translation to the payment status and status in the record payment.
#881 
1. Go to invoice
2. Select an item
3. Click on the 3 dots
4. Choose Record Payment
5. Change the language into one different than english
6. See that the status of the invoice as well as the payment status are in the chosen language
> fixed translation issue in RecordPayment (status and payment status)

- frontend/src/pages/Company/index.jsx
- frontend/src/pages/Customer/index.jsx
- frontend/src/pages/Email/index.jsx
Update the inconsistent function names exported from pages directory in these files:
```
src/pages/Company/index.jsx
src/pages/Customer/index.jsx
src/pages/Email/index.jsx
```
[Issue-892](https://github.com/idurar/idurar-erp-crm/issues/892)
- [] I have updated the relevant documentation
- [] I have commented my code, particularly in hard-to-understand areas
> refactor: use correct functions name with respect to the corresponding filenames

- frontend/src/redux/translate/reducer.js
Avoid overriding previous state translations data over new translations. 
File
```
frontend/src/redux/translate/reducer.js
```
Please provide a brief description of the changes or additions made in this pull request.
`      return {
result: { ...state.result, ...payload },
langCode: langCode.toLowerCase(),
langDirection: isRtl ? 'rtl' : 'ltr',
isLoading: false
}
`
This would make the translations data in the result dirty. 
Unless if there was a specific use case, due to which this is written like this {` ...state.result, ...payload }`, we should avoid destructuring of new translations over previous state translations. 
Because, when there are keys that are present in Hindi translation but are not present in English translation file, it would retain such keys and its values when we change …
> fix: avoid overriding of translations data from previous state

- frontend/src/components/DataTable/DataTable.jsx
- frontend/src/modules/ErpPanelModule/DataTable.jsx
closes: #923 
Removing the refresh text, and using the refresh icon only.
> feat: Remove Refresh button text , use icon only

- README.md
- backend/.env
I noticed a typo in the Getting Started section, Step 5: Install Backend Dependencies
It's written this way: 
**the urn** the following command to install the backend dependencies.
And i Changed it to :
In your terminal, run the following command to install the backend dependencies.
This pull request isn't related to any open issue
- [X ] I have tested these changes
- [X ] I have updated the relevant documentation
> Corrected a Typo in README.md file

- frontend/src/modules/AdminCrudModule/AdminDataTable.jsx
I noticed that both the "Show" and "Update Password" actions in the Admin List table were using the same icon, so i changed the Update Password's icon to a more suitable one using Ant Design.
_This is The Before:_
_This is the After:_
> Better icon for Admin Update Password

- frontend/src/modules/AdminCrudModule/index.jsx
The purpose of this pull request (PR) is to address the issue related to creating admin accounts. In earlier versions, creating a new admin account necessitated sending a multipart request. However, in this updated version, the requirement for an image associated with the admin account has been eliminated. Consequently, the request now only needs to be a straightforward create request rather than a createAndUpload request.
#983 
1. Login to the admin account using those credentials: email: admin@demo.com password: admin123
2. Navigate to the settings page using sidebar
3. Navigate tp the admin subcategory
4. Try to add a new admin
Here is the video of @ngtalexander of the issue that he faced:
https://github.com/idurar/idurar-erp-crm/assets/12747343/f6d12977-321b-4f04-a1da-1e9c4d5839fd …
> Fix: resolve admin create issue

- frontend/src/apps/Header/HeaderContainer.jsx
I noticed that both the "Profile Settings" and "App Settings" actions in the Avatar dropdown have the same icon, so i changed both icons for more suitable ones using Ant Design.
_This is the Before_
_This is the After_
> Enhanced profile setting icon for avatar drop down

- backend/src/controllers/appControllers/paymentController/create.js
Payment controller had multiple references to "req" object inside like ```req.req.req.body```  which caused adding payment method to fail and return internal server error. Probably a typo.
try recording payment to invoice
> fix 'req is undefined' error in payment controller

- backend/.env
- backend/src/utils/currency.js
- frontend/src/pages/Currency/currencyList.js
Added East Caribbean Dollar in the Currency Code and other fields
[Add East Caribbean Dollar Support #1054.](https://github.com/idurar/idurar-erp-crm/issues/1054)
Login to the portal.
Go to the settings section.
Go to Currency.
Try to add a new currency for the XCD currency code(Eastern Caribbean dollar).
(Before it was not present in the list when you search currency code to add it.)
Attached screenshot for your reference.
**Before:**
**Now**
**Tested**
- [✅ ] I have tested these changes
- [ ✅] I have updated the relevant documentation
- [ ✅] I have commented my code, particularly in hard-to-understand areas
- [ ✅] I have made corresponding changes to the codebase
- [ ✅] My changes generate no new warnings or errors
- [✅ ] The title of my pull request is clear and descriptive
> fix: added East Caribbean Dollar Support in currency utils

- backend/src/controllers/appControllers/clientController/remove.js
Unable to delete client despite absence of invoices or quotes #1025
Unable to delete client despite absence of invoices or quotes #1025
- Create a new user
- Create a client attached to that user, make sure that user is not associated with any invoice.
- Try deleting user. It must be get delete now.
- Try adding client with user associated with some invoice, try deleting client, it mustn't get delete.
N/A
> fix: resolve client delete issue
